# -*- coding: utf-8 -*-
"""amazon prime project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M2fWhB_QMQ_PFy55wkWk28KmB4UxaSz0

# Name-Kulesh Kumar Yadav
# Batch-DS2505B
# Project Name-Amazon Prime TV Shows and Movies
# Exploratory Data Analysis
# Github link--
"""









import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly as pl
import ast



df_credit=pd.read_csv("/content/credits.csv.zip")
df_credit.head()

df_credit.tail()

df_credit.duplicated().sum()

df_credit.drop_duplicates(inplace=True)

df_credit.duplicated().sum()

df_credit.shape

df_credit.isnull().mean()*100

100-(df_credit.dropna().shape[0]/df_credit.shape[0])*100

df_credit["character"].dtypes

df_credit["character"].value_counts()



df_credit["character"]=df_credit["character"].fillna("unknown")

df_credit["character"].isnull().sum()



df_title=pd.read_csv("/content/titles.csv.zip")
df_title.head(2)

df_title.tail(2)

df_title.shape

#findig the duplicates in df_title
df_title.duplicated().sum()

#droping the duplicates
df_title.drop_duplicates(inplace=True)

df_title.duplicated().sum()



#finding the null values
df_title.isnull().mean()*100



df_title[["description","age_certification","seasons","imdb_id","imdb_score","imdb_votes","tmdb_popularity","tmdb_score"]].isnull().mean()*100

# both the columns have more than 65% null values so have to drop both the columns
df_title.drop(["age_certification","seasons"],axis=1,inplace=True)

df_title.isnull().mean()*100

# this column has aprx 1% null values of total rows so am droping the rows where the null values are present
df_title.dropna(subset=["description"],inplace=True)

df_title.isnull().mean()*100

df_title.imdb_id.unique()

# this column is not necessary for analysis it has only id of imdb..so i am deleting this column
df_title.drop(columns=["imdb_id"],axis=1,inplace=True)

df_title.columns

# by using this code u can easily see the null values in data frame
df_title[df_title["imdb_score"].isnull()]

df_title["imdb_score"].value_counts()

df_title["imdb_score"].agg({"mean","median"})

df_title["imdb_score"].fillna(method="ffill",inplace=True)

df_title["imdb_score"].value_counts()

df_title["imdb_score"].agg({"mean","median"})

df_title.isnull().mean()*100

df_title["imdb_votes"].value_counts()

df_title["imdb_votes"].agg({"mean","median"})

df_title["imdb_votes"].fillna(method="ffill",inplace=True)

df_title["imdb_votes"].value_counts()

df_title["imdb_votes"].agg({"mean","median"})

df_title.isnull().mean()*100

df_title["tmdb_popularity"].value_counts()

df_title["tmdb_popularity"].fillna(df_title["tmdb_popularity"].median(),inplace=True)

df_title["tmdb_popularity"].isnull().sum()

df_title["tmdb_score"].isnull().mean()*100

df_title["tmdb_score"].describe()

df_title["tmdb_score"].fillna(df_title["tmdb_score"].median(),inplace=True)

df_title.isnull().sum()

df_credit.isnull().sum()

df_title.shape

df_title.head()



df_credit.shape

df_title.shape

df_credit.columns

df_title.columns

df=pd.merge(df_title,df_credit,on="id",how="inner")

df.head()

print(f"the total shape of each data frame--->merge data frame :{df.shape},dataframe of title:{df_title.shape},dataframe of credit:{df_credit.shape}")

df.info()

df.duplicated().sum()

df.drop_duplicates(inplace=True)

df.duplicated().sum()

df.head()



df.columns

df.isnull().sum()

null_value=["-","n/a","missing","N/A","null"]
df.replace(null_value,np.nan,inplace=True)

df.isnull().mean()

df.dropna().shape

df.shape

(df.dropna().shape[0]/df.shape[0])*100

df.columns

df.id

df.describe()

df.columns

df["title"].head()

df.groupby("title")["imdb_score"].max().reset_index()

df.groupby("title")["imdb_votes"].max().reset_index()

df.groupby("production_countries")["imdb_score"].agg({"max","mean"})
#The maximum rating given by the persons to the ['AF', 'US'] production_countries and mostly people are watching shows or movie of this ['AF', 'US'] production_countries  as well

df.groupby("production_countries")["imdb_votes"].agg({"max","mean"}).sort_values(by='max', ascending=False)
# here we can see that the maximum votes by the user goes to ['US', 'FR', 'IT'] production countries
# average voting goes to "US,FR,IT" as well

df.groupby("runtime")["imdb_score"].agg({"max","mean"}).sort_values(by='max', ascending=False)
# here runtime does not mattter to the idmb_score

df.groupby("type")["imdb_score"].agg({"max","mean"}).sort_values(by='max', ascending=False)
#the maximum rating given by the users to MOVIE but average persons are interested in shows



df["type"].value_counts()

plt.figure(figsize=(8, 5))
sns.histplot(df['imdb_score'], bins=20, kde=True)
plt.title('Histogram of imdb_score')
plt.xlabel('imdb_score')
plt.ylabel('Frequency')
plt.show()

"""the graph is symmetric...there is no skewness"""

plt.figure(figsize=(8, 5))
sns.histplot(df['imdb_votes'], bins=20, kde=True)
plt.title('Histogram of imdb_votes')
plt.xlabel('imdb_votes')
plt.ylabel('Frequency')
plt.show()

"""this data has outliers because its highly right skewed"""

plt.figure(figsize=(12,5))
sns.boxplot(x=df['imdb_votes'])
plt.title('Box Plot of imdb_votes')
plt.xlabel('imdb_votes')
plt.show()

Q1=df.imdb_votes.quantile(0.25)
Q2=df.imdb_votes.quantile(0.75)
IQR=Q2-Q1
print(f"Q1:{Q1}  Q2:{Q2}  IQR:{IQR} ")

LB=Q1-1.5*IQR
UB=Q2+1.5*IQR
print(f"Lower Bound : {LB} and Upper Bound :{UB}")

df[df.loc[:,"imdb_votes"]<LB]
#There is no data less than lower bound

df[df.loc[:,"imdb_votes"]>UB]
#there are lots of data which are greater then upper bound

# we have to remove those data which are above of upper bound
df.loc[df["imdb_votes"]>UB,"imdb_votes"]

(df.shape[0]/19927)
#here if i drop the outliers then 6% data will be lost...the best approach here is to fill the data by replacing it mean or median
# the data points are highly skewed towards right so i can replace with median

df.imdb_votes.median()

df.loc[df["imdb_votes"]>UB,"imdb_votes"]=df.imdb_votes.median()

df.loc[df["imdb_votes"]<LB,"imdb_votes"]=df.imdb_votes.median()

plt.figure(figsize=(8,5))
sns.boxplot(x=df['imdb_votes'])
plt.title('Box Plot of imdb_votes')
plt.xlabel('imdb_votes')
plt.show()

#here still outliers are present

df["imdb_votes"]=np.sqrt(df["imdb_votes"])

plt.figure(figsize=(8,5))
sns.boxplot(x=df['imdb_votes'])
plt.title('Box Plot of imdb_votes')
plt.xlabel('imdb_votes')
plt.show()

plt.figure(figsize=(8, 5))
sns.histplot(df['imdb_votes'], bins=20, kde=True)
plt.title('Histogram of imdb_votes')
plt.xlabel('imdb_votes')
plt.ylabel('Frequency')
plt.show()

df.groupby("production_countries")['imdb_score'].mean().sort_values(ascending=False)

df_production=df.production_countries.value_counts().reset_index()
df_production

production_count=df.production_countries.value_counts().reset_index().iloc[0:20]['production_countries']
count_1=df.production_countries.value_counts().reset_index().iloc[0:20]['count']
plt.figure(figsize=(15,5))
plt.xlabel("production countries")
plt.ylabel("Count")
plt.title("Production countries vs Count")
sns.barplot(x=production_count,y=count_1)

"""here...the maximum production is coming from US production"""

production_count=df.production_countries.value_counts().reset_index().iloc[0:-20]['production_countries'].sort_values(ascending=False)
production_count

# Convert string to list
df['production_country'] = df['production_countries'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)

# Flatten the list of genres
all_countries = [g for sublist in df['production_country'] for g in sublist]

# Convert to pandas Series and count
countries_counts = pd.Series(all_countries).value_counts()

country_count=countries_counts
TOP20_production_country=country_count.iloc[0:20]
TOP20_production_country.keys
TOP20_production_country.values
plt.figure(figsize=(15, 6))
sns.barplot(x=TOP20_production_country.keys(), y=TOP20_production_country.values, palette='viridis')
plt.xlabel('Name of the COuntries')
plt.ylabel('count')
plt.title('Distribution of production countries')
plt.show()

df['type'].value_counts()

plt.figure(figsize=(8,5))
sns.histplot(x=df["type"],bins=20)
plt.title("Hisogram of type ")
plt.xlabel("type")
plt.ylabel("count")

sns.set_style("whitegrid")
types_of_type = df['type'].value_counts()
types_of_type
plot = types_of_type.plot.pie(x = 'MOVIE', y='SHOW', autopct='%1.1f%%', figsize=(8, 8))

"""as campare to movie very less no. of shows are available"""

plt.figure(figsize=(8,5))
sns.barplot(x=df.type, y=df.imdb_score, palette="viridis")
plt.xlabel("type")
plt.ylabel("imdb_score")
plt.title("Type vs Imdb score")
plt.show()

"""According to imdb_score...shows are getting more rating than Movies."""



plt.figure(figsize=(8,5))
sns.histplot(x=df["role"],bins=20)



df.groupby("genres")["imdb_score"].agg({"max","min","mean"}).sort_values(by='max', ascending=False)

""" -action,drama,and history these types of shows or movie is mostly watched
 and also gained maximum voting

 -most dominating part of the genres is 'drama'
"""

# Convert string to list
df['genres'] = df['genres'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)

# Flatten the list of genres
all_genres = [g for sublist in df['genres'] for g in sublist]

# Convert to pandas Series and count
genre_counts = pd.Series(all_genres).value_counts()


# Creating a grouped bar chart
plt.figure(figsize=(15, 6))
sns.barplot(x=genre_counts.keys(), y=genre_counts.values, palette='viridis')
plt.xlabel('no. of genres')
plt.ylabel('count')
plt.title('Distribution of Titles by genres')
plt.show()

most_20_shows_movies=df.title.value_counts().sort_values(ascending=False)
top_20=most_20_shows_movies.iloc[:15]
plt.figure(figsize=(20, 4))
sns.barplot(x=top_20.keys(), y=top_20.values, palette='viridis')
plt.xlabel('top_20_movies or shows')
plt.ylabel('count')
plt.title('Distribution of top 20 movies or shows')
plt.show()

df.columns



df['tmdb_popularity']



"""# **Conclusion**--------
# 1) No. of shows are very less as comapre to No. of movie
# 2) action,drama,and history these types of shows or movie is mostly watched      and also gained maximum voting

# 3) most dominating part of the genres is 'drama'
# 4) the maximum rating given by the users to MOVIE but average persons are interested in shows
# 5) the maximum production is coming from US production



"""





















